題目:<br>
array1 = np.array([[10, 8], [3, 5]])<br>

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?<br>
運用上列array計算特徵值、特徵向量?<br>
運用上列array計算SVD?<br>

In [1]:
import numpy as np

In [2]:
array1 = np.array([[10,8],[3,5]])
array0 = np.linalg.inv(array1)
print("inverse array:","\n",array0,"\n")
print(array0 @ array1)

inverse array: 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]] 

[[1. 0.]
 [0. 1.]]


In [3]:
w,v = np.linalg.eig(array1)
print("特徵值:",w,"\n")
print("特徵向量:","\n",v)

特徵值: [13.  2.] 

特徵向量: 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [4]:
u,s,vh = np.linalg.svd(array1)
print(u,"\n")
print(s,"\n")
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 

[13.94721714  1.86417116] 

[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
