題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [1]:
import numpy as np

array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('array.npz','wb') as f:
    np.savez(f, arr1 = array1, arr2 = array2)

In [2]:
print("array.npz")
npzfile = np.load('array.npz') 
print(npzfile['arr1'])
print(npzfile['arr2'])
print("-------------------------")

array3 = np.random.randint(1,10,4)
np.savez('new.npz',arr1 = npzfile['arr1'],arr2 = npzfile['arr2'], arr3 = array3)
npzfile2 = np.load('new.npz') 
print("new.npz")
print(npzfile2['arr1'])
print(npzfile2['arr2'])
print(npzfile2['arr3'])

array.npz
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
-------------------------
new.npz
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[3 2 5 2]
